sudo: required
language: go
go:
- '1.9'
services:
- docker
addons:
  apt:
    packages:
    - docker-ce
before_install: 
script:
- "./build.sh"
- "./contrib/ci.sh"
before_deploy:
- "./ci/hashgen.sh"
deploy:
  provider: releases
  api_key:
    secure: OVkqAdlgUNM/JhmDe20iqFpQj28qAFzKmxBbWW5oC5N8dHenHFlNtfkESoibvEOSzSLRFrUe0FjDorrUW6fXrTGyrsFGJP1NeSXA7KyeSXg8K/m/z5u4fKNmW5U1oAHeHMzmJeLC2uvXvaL8lm/Zw9zhe/anCXjR+zxN37jCKpzL0nIgniROYLFVc58+J7U0DlcnUi1eROa1P0VpBgVBCFOjSxyV507OVhzEHHE75ZcrzhWRm8yzBkEONFz9a8fhTJiypsTQyyuZmtPe+kVtWqk+PfZu2lPbORJQOTeCHE8p1pkbqMlgy0rrgObU/Vn+ZzcAyP+VgJ31uoaaG4cd1Z9I38WxDqKBM4BpKGgXUINkdvLXxYCGpi/JMkVS4tWqQq+k0ohd+GUKIq4HXhzUWFlfpfffUeB2ikxIxvZcKuCAJz4r1H6UhebSTwgg7DSckD19E23sOE3b7qCqqYWkAoKq2fNNkkRWORbwYwuqFqe6eLfqtjEuO/DtgSzSdPoRo93GR8dL1BWxuNwYJEkf793ERgVDROXXXHJhE87sYuB6v0unUKNprWvsa9d/9n5Sa6WnRIqKNd2tBU/4txPrNWrdeFBXSdKjHNE2irXJPF5SEnJwZsnoHhchRv+Ypf16ImXT22pvmQoXGfjP4ewUU/Q1T8/2CUJ33uU/x2xVL/M=
  file:
  - "./watchdog/fwatchdog"
  - "./watchdog/fwatchdog-armhf"
  - "./watchdog/fwatchdog-arm64"
  - "./watchdog/fwatchdog.exe"
  - "./watchdog/fwatchdog.sha256"
  - "./watchdog/fwatchdog-armhf.sha256"
  - "./watchdog/fwatchdog-arm64.sha256"
  - "./watchdog/fwatchdog.exe.sha256"
  skip_cleanup: true
  on:
    tags: true
